#
# This file is part of AtomVM.
#
# Copyright 2026 Davide Bettio <davide@uninstall.it>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0 OR LGPL-2.1-or-later
#

if(DEFINED DEF_FILE AND DEFINED OUT_FILE AND DEFINED PREFIX)
    # Executed in script mode: cmake -DDEF_FILE=... -DOUT_FILE=... -DPREFIX=... -P GenDefaultAtoms.cmake

    file(STRINGS "${DEF_FILE}" LINES)

    set(ATOM_COUNT 0)
    set(MIN_LEN 999)
    set(MAX_LEN 0)

    foreach(line ${LINES})
        if(line MATCHES "^[ \t]*X[ \t]*\\([ \t]*([A-Za-z0-9_]+)[ \t]*,[ \t]*\"[^\"]*\"[ \t]*,[ \t]*\"([^\"]*)\"[ \t]*\\)")
            set(ATOM_STR "${CMAKE_MATCH_2}")
            string(LENGTH "${ATOM_STR}" ATOM_LEN)

            if(ATOM_LEN LESS MIN_LEN)
                set(MIN_LEN ${ATOM_LEN})
            endif()
            if(ATOM_LEN GREATER MAX_LEN)
                set(MAX_LEN ${ATOM_LEN})
            endif()

            # Format: "<atom_str>:<index>"
            list(APPEND BUCKET_${ATOM_LEN} "${ATOM_STR}:${ATOM_COUNT}")
            math(EXPR ATOM_COUNT "${ATOM_COUNT} + 1")
        endif()
    endforeach()

    if(ATOM_COUNT EQUAL 0)
        set(MIN_LEN 0)
        set(MAX_LEN 0)
    endif()

    # Sort each bucket alphabetically and build arrays
    set(ALL_INDICES "")
    set(OFFSETS "")
    set(CURRENT_OFFSET 0)

    math(EXPR MAX_LEN_PLUS_1 "${MAX_LEN} + 1")
    foreach(L RANGE 0 ${MAX_LEN_PLUS_1})
        list(APPEND OFFSETS ${CURRENT_OFFSET})
        if(DEFINED BUCKET_${L})
            list(SORT BUCKET_${L} COMPARE STRING CASE SENSITIVE ORDER ASCENDING)
            foreach(item ${BUCKET_${L}})
                string(REGEX REPLACE "^.*:([0-9]+)$" "\\1" IDX "${item}")
                list(APPEND ALL_INDICES ${IDX})
                math(EXPR CURRENT_OFFSET "${CURRENT_OFFSET} + 1")
            endforeach()
        endif()
    endforeach()

    list(LENGTH OFFSETS NUM_OFFSETS)
    list(LENGTH ALL_INDICES NUM_INDICES)

    string(TOUPPER "${PREFIX}" UPPER_PREFIX)

    if(ATOM_COUNT GREATER 255)
        set(INDEX_TYPE "uint16_t")
    else()
        set(INDEX_TYPE "uint8_t")
    endif()

    set(CONTENT "/* Automatically generated by GenDefaultAtoms.cmake. DO NOT EDIT. */\n\n")
    string(APPEND CONTENT "#ifndef _${UPPER_PREFIX}_DEFAULTATOMS_TABLES_H_\n")
    string(APPEND CONTENT "#define _${UPPER_PREFIX}_DEFAULTATOMS_TABLES_H_\n\n")
    string(APPEND CONTENT "#include <stdint.h>\n\n")
    string(APPEND CONTENT "#define ${UPPER_PREFIX}_DEFAULTATOMS_COUNT ${ATOM_COUNT}\n")
    string(APPEND CONTENT "#define ${UPPER_PREFIX}_DEFAULTATOMS_MIN_LEN ${MIN_LEN}\n")
    string(APPEND CONTENT "#define ${UPPER_PREFIX}_DEFAULTATOMS_MAX_LEN ${MAX_LEN}\n\n")

    # len_offsets table
    string(APPEND CONTENT "static const ${INDEX_TYPE} ${PREFIX}_len_offsets[${NUM_OFFSETS}] = {\n    ")
    set(COL 0)
    foreach(off ${OFFSETS})
        string(APPEND CONTENT "${off}, ")
        math(EXPR COL "${COL} + 1")
        if(COL EQUAL 16)
            string(APPEND CONTENT "\n    ")
            set(COL 0)
        endif()
    endforeach()
    string(APPEND CONTENT "\n};\n\n")

    # atoms_by_len table
    if(NUM_INDICES GREATER 0)
        string(APPEND CONTENT "static const ${INDEX_TYPE} ${PREFIX}_atoms_by_len[${NUM_INDICES}] = {\n")
        foreach(L RANGE ${MIN_LEN} ${MAX_LEN})
            if(DEFINED BUCKET_${L})
                list(LENGTH BUCKET_${L} BLEN)
                string(APPEND CONTENT "    // Len ${L} (${BLEN} atoms)\n    ")
                set(COL 0)
                foreach(item ${BUCKET_${L}})
                    string(REGEX REPLACE "^.*:([0-9]+)$" "\\1" IDX "${item}")
                    string(APPEND CONTENT "${IDX}, ")
                    math(EXPR COL "${COL} + 1")
                    if(COL EQUAL 16)
                        string(APPEND CONTENT "\n    ")
                        set(COL 0)
                    endif()
                endforeach()
                string(APPEND CONTENT "\n")
            endif()
        endforeach()
        string(APPEND CONTENT "};\n\n")
    else()
        string(APPEND CONTENT "static const ${INDEX_TYPE} ${PREFIX}_atoms_by_len[1] = { 0 };\n\n")
    endif()

    string(APPEND CONTENT "#endif /* _${UPPER_PREFIX}_DEFAULTATOMS_TABLES_H_ */\n")

    # Write only if changed to avoid unnecessary rebuilds
    set(SHOULD_WRITE TRUE)
    if(EXISTS "${OUT_FILE}")
        file(READ "${OUT_FILE}" EXISTING_CONTENT)
        if("${EXISTING_CONTENT}" STREQUAL "${CONTENT}")
            set(SHOULD_WRITE FALSE)
        endif()
    endif()

    if(SHOULD_WRITE)
        file(WRITE "${OUT_FILE}" "${CONTENT}")
    endif()

else()
    # Included as CMake module
    set(GEN_DEFAULT_ATOMS_SCRIPT "${CMAKE_CURRENT_LIST_FILE}" CACHE INTERNAL "")

    function(generate_defaultatoms TARGET_NAME DEF_FILE OUT_FILE PREFIX)
        get_filename_component(OUT_DIR "${OUT_FILE}" DIRECTORY)
        add_custom_command(
            OUTPUT "${OUT_FILE}"
            COMMAND ${CMAKE_COMMAND}
                -DDEF_FILE=${DEF_FILE}
                -DOUT_FILE=${OUT_FILE}
                -DPREFIX=${PREFIX}
                -P "${GEN_DEFAULT_ATOMS_SCRIPT}"
            DEPENDS
                "${DEF_FILE}"
                "${GEN_DEFAULT_ATOMS_SCRIPT}"
            COMMENT "Generating ${OUT_FILE} from ${DEF_FILE}"
        )
        add_custom_target(${TARGET_NAME}_${PREFIX}_defaultatoms_tables DEPENDS "${OUT_FILE}")
        add_dependencies(${TARGET_NAME} ${TARGET_NAME}_${PREFIX}_defaultatoms_tables)
        target_include_directories(${TARGET_NAME} PRIVATE "${OUT_DIR}")
    endfunction()
endif()
